# Generated by Django 2.1 on 2019-12-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='xDPI_upload_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('file_name', models.CharField(max_length=100)),
                ('upload_date', models.DateTimeField(blank=True, null=True)),
                ('file_size', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'xDPI_upload_history',
                'managed': True,
            },
        ),
    ]
