# Generated by Django 2.1 on 2019-12-12 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xdpi_upload_history',
            name='upload_id',
        ),
    ]
